# Generated by Django 6.0.2 on 2026-02-10 16:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cards', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='hint_text',
        ),
    ]
